// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmlloboagxgjyhtahvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWxsb2JvYWd4Z2p5aHRhaHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTU3NTAsImV4cCI6MjA2NjE3MTc1MH0.1ePoPeoyibTIym2_cwmVWGGGi1u3tp4hIa1nxSdSUjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
